#!/bin/bash

# Get command
cmd=$1

# Run command
case $cmd in 

    create_venv)
    read -p "Please type venv folder path (leave empty if you want to use default settings): " venv_location
    ci/create_venv.sh $venv_location
    ;;

    activate_venv)
    read -p "Please type your venv folder path (leave empty if you use default settings): " venv_location
    ci/activate_venv.sh $venv_location
    ;;

    run)
    ci/start_bot.sh
    ;;

    install)
    ci/install_runtime.sh
    ;;

    setup_dev)
    ci/install_runtime.sh
    ci/install_dev.sh
    ;;

    *)
    if [[ $cmd -eq "" ]]
    then
        echo "No command specified."
    else
        echo "Command not found."
    fi
    ;;

esac
